add_newline = true 
command_timeout = 1000 
scan_timeout = 30 # timeout for file scan

# ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®è¡¨ç¤ºé †åº
format = """
$username\
$directory\
$git_branch\
$git_status\
$aws\
$gcloud\
$docker_context\
$nodejs\
$python\
$rust\
$golang\
$cmd_duration\
$line_break\
$character"""

[character]
error_symbol = "[x](bold red)"
success_symbol = "[>](bold green)"
vimcmd_symbol = "[<](bold green)"

[directory]
truncate_to_repo = false
truncation_length = 5
truncation_symbol = "â€¦/"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[cmd_duration]
format = "took [$duration]($style) " 
min_time = 2000 # 2ç§’ä»¥ä¸Šã§è¡¨ç¤º

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
symbol = "ï¸ðŸ‡¦ï¸ "

[aws.region_aliases]
ap-northeast-1 = "jp"

[gcloud]
format = '[$symbol$active]($style) '
style = 'bold yellow'
symbol = 'ï¸ðŸ‡¬ï¸ '

[docker_context]
format = "via [ðŸ‹ $context](blue bold)"

[nodejs]
format = "via [$symbol($version )]($style)"
symbol = " "

[python]
format = "via [$symbol($version )]($style)"
symbol = " "

[rust]
format = "via [$symbol($version )]($style)"
symbol = " "

[golang]
format = "via [$symbol($version )]($style)"
symbol = " "

[username]
disabled = false
format = "[$user ðŸŒ±]($style) "
show_always = true
style_root = "black bold"
style_user = "white bold"

[time]
disabled = true
